# https://github.com/eslint/eslint
eslint:
  enabled: true
  config_file: .eslintrc

# https://github.com/jshint/jshint
jshint:
  enabled: true
  config_file: .jshintrc

# # https://github.com/bbatsov/rubocop
ruby:
  enabled: true
  config_file: .rubocop.yml

# https://github.com/brigade/scss-lint/
scss:
  enabled: true
  config_file: .scss-lint.yml
