AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - "bin/**/*"
    - "db/migrate/**/*"
    - "spec/dummy/**/*"
    - "config/initializers/devise.rb"
    - "config/initializers/simple_form.rb"
    - "config/initializers/simple_form_bootstrap.rb"

Metrics/BlockLength:
  Exclude:
    - '**/*.rake'
    - 'config/routes.rb'
    - 'lib/archangel/testing_support/**/*.rb'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 80

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: leading

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
