# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
AllCops:
  Include:
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'bin/**/*'
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'db/migrate/**/*'
    - 'spec/dummy/**/*'
    - 'vendor/**/*'

Layout/DotPosition:
  EnforcedStyle: leading

Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - '**/*.rake'
    - 'config/routes.rb'
    - 'lib/archangel/testing_support/**/*.rb'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 80

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '[]'
    '%I': '[]'
    '%r': '{}'
    '%w': '[]'
    '%W': '[]'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: percent
