# https://raw.githubusercontent.com/bbatsov/rubocop/master/config/default.yml
AllCops:
  Include:
    - '**/*.rake'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'bin/**/*'
    - 'db/migrate/**/*'
    - 'spec/dummy/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - '**/*.rake'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/routes.rb'
    - 'archangel.gemspec'
    - 'lib/archangel/testing_support/**/*.rb'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 80

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: leading

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
