# https://github.com/brigade/scss-lint/blob/master/config/default.yml
scss_files:
  - 'app/assets/stylesheets/**/*.scss'

exclude:
  - 'vendor/assets/stylesheets/**'

linters:
  Indentation:
    character: space
    width: 4
  StringQuotes:
    style: single_quotes
