language: ruby
bundler_args: --without production --quiet
before_install:
  - gem update --system
  - gem --version
install: ruby -S bundle install
script:
  - bundle exec rake dummy_app
  - bundle exec rake spec
rvm:
  - 2.2.3
  - 2.2.7
  - 2.3.4
  - 2.4.1
