# frozen_string_literal: true

source "https://rubygems.org"

gem "archangel", github: "archangel/archangel", branch: "master"

gemspec

group :development do
  gem "rubocop", "~> 0.48.1"
end

group :development, :test do
  gem "pry-byebug", "~> 3.4.2"
  gem "sqlite3", ">= 1.3.0", platforms: %i[ruby mswin mswin64 mingw x64_mingw]
end

group :test do
  gem "capybara", "~> 2.13.0"
  gem "coveralls", "~> 0.8.20"
  gem "database_cleaner", "~> 1.5.3"
  gem "factory_girl_rails", "~> 4.8.0"
  gem "launchy", "~> 2.4.3"
  gem "poltergeist", "~> 1.14.0"
  gem "rails-controller-testing", "~> 1.0.1"
  gem "rspec-rails", "~> 3.5.2"
  gem "shoulda-callback-matchers", "~> 1.1.4"
  gem "shoulda-matchers", "~> 3.1.1"
  gem "simplecov", "~> 0.14.1"
end
